/*
PRO: Implement a robust response parser and file writer for ShiningDocs.

Goal:
Create a module that converts large LLM response text into safe, well-structured files on disk,
with backups, path-safety, and clear user feedback.

Exported function:
  async function parseAndWriteDocs(responseText: string, targetRoot: vscode.Uri, options?: {
    overwrite?: boolean, backup?: boolean, maxFileSize?: number
  }): Promise<{writtenFiles: string[], backups: string[], warnings: string[]}>;

Requirements:

1) File Marker Parsing
- Recognize explicit markers in the LLM output:
    ---FILE: path/to/file.md---
    (file contents)
- Accept multiple marker syntaxes (case-insensitive), e.g.:
    --- FILE: README.md ---
    <<<FILE: docs/index.md>>>
- Trim leading/trailing whitespace from each file content.
- If no markers are present:
    - Create README.md with full content.
    - Create docs/index.md with a short split (first section → index, rest → README) if the content is large.

2) Path Safety & Normalization
- Restrict target paths to be inside `targetRoot` only.
- Normalize paths, reject any with `..` or absolute drive roots.
- Ensure directories are created (`vscode.workspace.fs.createDirectory`) before writing.
- Sanitize filenames to remove unsafe characters.

3) Backup & Idempotency
- If a file exists and `overwrite` is false:
    - Create backup: `<filename>.bak.<ISOtimestamp>` and copy original contents first.
- If `overwrite` true, still create one backup by default (unless `backup: false`).
- Ensure atomic write: write to a `.tmp` file then rename/replace.

4) File Size Limits
- Respect `maxFileSize` option (default 2,000,000 bytes). If a parsed file exceeds limit:
    - Split into parts: `file.part1.md`, `file.part2.md`, ... and add a warning entry.
- If the LLM returns binary or non-text content, skip with a warning.

5) Markdown Sanitization & Frontmatter
- If the file starts with YAML frontmatter (`---`), preserve it.
- Optionally (configurable), inject a short auto-generated footer comment:
   `<!-- Generated by ShiningDocs on <timestamp> — please review -->`

6) Logging & User Feedback
- Write progress & warnings to the "ShiningDocs" output channel.
- On success show `vscode.window.showInformationMessage("ShiningDocs: Generated X files")`.
- On fatal errors show `vscode.window.showErrorMessage(...)` with action button "Open Output".

7) Tests & Edge Cases
- Include internal helper functions exported for testing:
   - `extractFilesFromText(text: string): Array<{path: string, content: string}>`
   - `safeJoinRoot(root: Uri, relPath: string): Uri|null` (returns null if unsafe)
- Add JSDoc comments and TypeScript types for all exported symbols.

8) Example behaviors:
- Input:
    ---FILE: README.md---
    # Project
    ---FILE: docs/installation.md---
    Steps...
  Output: files written at `targetRoot/README.md` and `targetRoot/docs/installation.md`, backups if needed.

9) Implementation constraints:
- No external NPM libs (use std VS Code FS and Node utils).
- Use async/await and proper try/catch.
- Keep code modular and unit-test-friendly.
- Mark TODOs for streaming chunk handling (future work).

Return value:
  { writtenFiles: string[], backups: string[], warnings: string[] }

Quality bar:
- Safe, atomic writes
- Clear logs and user messages
- Fully typed, ready for unit tests
*/

import * as vscode from 'vscode';
import * as path from 'path';

const MAX_FILE_SIZE_DEFAULT = 2000000; // 2MB
const FOOTER_COMMENT = '<!-- Generated by ShiningDocs on {timestamp} — please review -->';

/**
 * Options for the parseAndWriteDocs function
 */
export interface ParseAndWriteOptions {
    /** Whether to overwrite existing files (default: true) */
    overwrite?: boolean;
    /** Whether to create backups (default: true) */
    backup?: boolean;
    /** Maximum file size in bytes (default: 2,000,000) */
    maxFileSize?: number;
    /** Whether to add footer comment (default: true) */
    addFooter?: boolean;
}

/**
 * Result of the parse and write operation
 */
export interface ParseAndWriteResult {
    /** List of successfully written file paths (relative to targetRoot) */
    writtenFiles: string[];
    /** List of backup file paths created */
    backups: string[];
    /** List of warnings encountered during processing */
    warnings: string[];
}

/**
 * Represents a parsed file with its path and content
 */
export interface ParsedFile {
    /** Relative path to the file */
    path: string;
    /** File content as string */
    content: string;
}

/**
 * Main function to parse LLM response text and write files to disk
 * @param responseText The raw text response from the LLM
 * @param targetRoot The root directory URI where files should be written
 * @param options Configuration options
 * @returns Promise resolving to operation results
 */
export async function parseAndWriteDocs(
    responseText: string,
    targetRoot: vscode.Uri,
    options: ParseAndWriteOptions = {}
): Promise<ParseAndWriteResult> {
    const outputChannel = vscode.window.createOutputChannel('ShiningDocs');
    const result: ParseAndWriteResult = {
        writtenFiles: [],
        backups: [],
        warnings: []
    };

    try {
        // Set defaults
        const opts = {
            overwrite: true,
            backup: true,
            maxFileSize: MAX_FILE_SIZE_DEFAULT,
            addFooter: true,
            ...options
        };

        outputChannel.appendLine('📝 Parsing LLM response...');

        // Extract files from response text
        const parsedFiles = extractFilesFromText(responseText);

        if (parsedFiles.length === 0) {
            // No markers found, create default structure
            outputChannel.appendLine('⚠️  No file markers found, creating default structure...');
            const defaultFiles = createDefaultStructure(responseText);
            parsedFiles.push(...defaultFiles);
        }

        outputChannel.appendLine(`📁 Found ${parsedFiles.length} files to write`);

        // Process each file
        for (const file of parsedFiles) {
            try {
                await processFile(file, targetRoot, opts, result, outputChannel);
            } catch (error) {
                const warning = `Failed to process file ${file.path}: ${error}`;
                result.warnings.push(warning);
                outputChannel.appendLine(`❌ ${warning}`);
            }
        }

        // Show success message
        const successMsg = `ShiningDocs: Generated ${result.writtenFiles.length} files`;
        vscode.window.showInformationMessage(successMsg, 'Open Output').then(selection => {
            if (selection === 'Open Output') {
                outputChannel.show();
            }
        });

        outputChannel.appendLine(`✅ Operation complete: ${result.writtenFiles.length} files written, ${result.backups.length} backups created`);

    } catch (error) {
        const errorMsg = `ShiningDocs: Fatal error during file processing: ${error}`;
        vscode.window.showErrorMessage(errorMsg, 'Open Output').then(selection => {
            if (selection === 'Open Output') {
                outputChannel.show();
            }
        });
        outputChannel.appendLine(`💥 ${errorMsg}`);
        result.warnings.push(`Fatal error: ${error}`);
    }

    return result;
}

/**
 * Extract files from text using various marker syntaxes
 * @param text The raw response text
 * @returns Array of parsed files
 */
export function extractFilesFromText(text: string): ParsedFile[] {
    const files: ParsedFile[] = [];

    // Multiple marker patterns to support
    const patterns = [
        /---\s*FILE:\s*([^\n]+)\s*---/gi,  // ---FILE: path---
        /<<<\s*FILE:\s*([^\n]+)\s*>>>/gi,  // <<<FILE: path>>>
        /```\s*FILE:\s*([^\n]+)\s*```/gi,   // ```FILE: path```
        /\[FILE:\s*([^\n]+)\]/gi            // [FILE: path]
    ];

    let combinedPattern = '';
    patterns.forEach((pattern, index) => {
        if (index > 0) combinedPattern += '|';
        combinedPattern += pattern.source;
    });

    const fileRegex = new RegExp(combinedPattern, 'gi');
    const lines = text.split('\n');
    let currentFile: ParsedFile | null = null;
    let contentStart = -1;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (!line) continue;

        const match = fileRegex.exec(line);

        if (match) {
            // Find the first non-undefined capture group (file path)
            const filePath = match.slice(1).find(group => group !== undefined)?.trim();
            if (!filePath) continue;

            // Save previous file if exists
            if (currentFile && contentStart >= 0) {
                currentFile.content = lines.slice(contentStart, i).join('\n').trim();
                files.push(currentFile);
            }

            // Start new file
            currentFile = {
                path: filePath,
                content: ''
            };
            contentStart = i + 1;
        }
    }

    // Save last file
    if (currentFile && contentStart >= 0) {
        currentFile.content = lines.slice(contentStart).join('\n').trim();
        files.push(currentFile);
    }

    return files;
}

/**
 * Create default file structure when no markers are found
 * @param content The full response content
 * @returns Array of default files
 */
function createDefaultStructure(content: string): ParsedFile[] {
    const files: ParsedFile[] = [];

    // If content is small, just create README.md
    if (content.length < 10000) {
        files.push({
            path: 'README.md',
            content: content
        });
        return files;
    }

    // Split large content: first section to docs/index.md, rest to README.md
    const sections = content.split(/^#+\s/m);
    if (sections.length > 1) {
        // First section (usually introduction) goes to docs/index.md
        const firstSection = sections[0] + '# ' + (sections[1]?.split('\n')[0] || 'Introduction');
        files.push({
            path: 'docs/index.md',
            content: firstSection.trim()
        });

        // Rest goes to README.md
        const restContent = sections.slice(1).join('# ').trim();
        files.push({
            path: 'README.md',
            content: restContent
        });
    } else {
        // Fallback: split by paragraphs
        const paragraphs = content.split('\n\n');
        const splitPoint = Math.min(5, Math.floor(paragraphs.length / 3));

        const indexContent = paragraphs.slice(0, splitPoint).join('\n\n');
        const readmeContent = paragraphs.slice(splitPoint).join('\n\n');

        files.push({
            path: 'docs/index.md',
            content: indexContent
        });
        files.push({
            path: 'README.md',
            content: readmeContent
        });
    }

    return files;
}

/**
 * Safely join a relative path to a root URI, ensuring it's within bounds
 * @param root The root directory URI
 * @param relPath The relative path to join
 * @returns The joined URI or null if unsafe
 */
export function safeJoinRoot(root: vscode.Uri, relPath: string): vscode.Uri | null {
    try {
        // Normalize the path
        const normalized = path.normalize(relPath).replace(/\\/g, '/');

        // Reject absolute paths or paths with .. that go outside root
        if (path.isAbsolute(normalized) || normalized.includes('../') || normalized.startsWith('/')) {
            return null;
        }

        // Sanitize filename (remove dangerous characters)
        const sanitized = normalized.replace(/[<>:"|?*\x00-\x1f]/g, '_');

        // Join with root
        const joined = vscode.Uri.joinPath(root, sanitized);

        // Ensure the result is still within the root (basic check)
        const rootPath = root.fsPath.toLowerCase();
        const joinedPath = joined.fsPath.toLowerCase();

        if (!joinedPath.startsWith(rootPath)) {
            return null;
        }

        return joined;
    } catch (error) {
        return null;
    }
}

/**
 * Process a single file: validate path, handle backups, write content
 */
async function processFile(
    file: ParsedFile,
    targetRoot: vscode.Uri,
    options: Required<ParseAndWriteOptions>,
    result: ParseAndWriteResult,
    outputChannel: vscode.OutputChannel
): Promise<void> {
    // Validate and join path
    const targetUri = safeJoinRoot(targetRoot, file.path);
    if (!targetUri) {
        const warning = `Unsafe or invalid path: ${file.path}`;
        result.warnings.push(warning);
        outputChannel.appendLine(`⚠️  ${warning}`);
        return;
    }

    // Check if file exists
    let fileExists = false;
    try {
        await vscode.workspace.fs.stat(targetUri);
        fileExists = true;
    } catch (error) {
        // File doesn't exist, which is fine
    }

    // Handle backups
    if (fileExists && options.backup) {
        const backupUri = await createBackup(targetUri, outputChannel);
        if (backupUri) {
            result.backups.push(vscode.workspace.asRelativePath(backupUri));
        }
    }

    // Check overwrite permission
    if (fileExists && !options.overwrite) {
        const warning = `File exists and overwrite disabled: ${file.path}`;
        result.warnings.push(warning);
        outputChannel.appendLine(`⚠️  ${warning}`);
        return;
    }

    // Process content
    let processedContent = file.content;

    // Add footer if requested
    if (options.addFooter) {
        const timestamp = new Date().toISOString();
        const footer = FOOTER_COMMENT.replace('{timestamp}', timestamp);
        processedContent += '\n\n' + footer;
    }

    // Check file size and split if necessary
    const contentBytes = Buffer.byteLength(processedContent, 'utf8');
    if (contentBytes > options.maxFileSize) {
        await splitLargeFile(targetUri, processedContent, options.maxFileSize, targetRoot, result, outputChannel);
        return;
    }

    // Write file atomically
    await writeFileAtomically(targetUri, processedContent, outputChannel);

    // Record success
    const relativePath = vscode.workspace.asRelativePath(targetUri);
    result.writtenFiles.push(relativePath);
    outputChannel.appendLine(`✅ Wrote ${relativePath} (${contentBytes} bytes)`);
}

/**
 * Create a backup of an existing file
 */
async function createBackup(originalUri: vscode.Uri, outputChannel: vscode.OutputChannel): Promise<vscode.Uri | null> {
    try {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const originalPath = originalUri.fsPath;
        const ext = path.extname(originalPath);
        const base = path.basename(originalPath, ext);
        const dir = path.dirname(originalPath);

        const backupName = `${base}.bak.${timestamp}${ext}`;
        const backupUri = vscode.Uri.file(path.join(dir, backupName));

        await vscode.workspace.fs.copy(originalUri, backupUri, { overwrite: true });
        outputChannel.appendLine(`📋 Backed up to ${path.basename(backupUri.fsPath)}`);

        return backupUri;
    } catch (error) {
        outputChannel.appendLine(`⚠️  Failed to create backup: ${error}`);
        return null;
    }
}

/**
 * Split a large file into multiple parts
 */
async function splitLargeFile(
    targetUri: vscode.Uri,
    content: string,
    maxSize: number,
    targetRoot: vscode.Uri,
    result: ParseAndWriteResult,
    outputChannel: vscode.OutputChannel
): Promise<void> {
    const contentBytes = Buffer.byteLength(content, 'utf8');
    const parts = Math.ceil(contentBytes / maxSize);

    const ext = path.extname(targetUri.fsPath);
    const base = path.basename(targetUri.fsPath, ext);
    const dir = path.dirname(targetUri.fsPath);

    outputChannel.appendLine(`📄 Splitting large file (${contentBytes} bytes) into ${parts} parts`);

    for (let i = 0; i < parts; i++) {
        const start = i * maxSize;
        const end = Math.min((i + 1) * maxSize, contentBytes);
        const partContent = content.substring(start, end);

        const partName = `${base}.part${i + 1}${ext}`;
        const partUri = vscode.Uri.file(path.join(dir, partName));

        await writeFileAtomically(partUri, partContent, outputChannel);

        const relativePath = vscode.workspace.asRelativePath(partUri);
        result.writtenFiles.push(relativePath);
    }

    const warning = `File ${vscode.workspace.asRelativePath(targetUri)} was split into ${parts} parts due to size limit`;
    result.warnings.push(warning);
}

/**
 * Write a file atomically using a temporary file
 */
async function writeFileAtomically(
    targetUri: vscode.Uri,
    content: string,
    outputChannel: vscode.OutputChannel
): Promise<void> {
    const tempUri = vscode.Uri.file(targetUri.fsPath + '.tmp');

    try {
        // Ensure directory exists
        const dirUri = vscode.Uri.file(path.dirname(targetUri.fsPath));
        await vscode.workspace.fs.createDirectory(dirUri);

        // Write to temporary file
        await vscode.workspace.fs.writeFile(tempUri, Buffer.from(content, 'utf8'));

        // Atomic rename/move
        await vscode.workspace.fs.rename(tempUri, targetUri, { overwrite: true });

    } catch (error) {
        // Clean up temp file on error
        try {
            await vscode.workspace.fs.delete(tempUri);
        } catch (cleanupError) {
            // Ignore cleanup errors
        }
        throw error;
    }
}

// TODO: Implement streaming chunk handling for very large responses
// TODO: Add support for binary file detection and skipping
// TODO: Add YAML frontmatter validation and enhancement
// TODO: Implement file content validation (e.g., check for valid Markdown)